name: ci

on:
  pull_request:
    branches:
      - main

jobs:
  module-validation:
    name: Module Validation
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Format Check
      run: terraform fmt -check -recursive

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

  examples-validation:
    name: Examples Validation
    runs-on: ubuntu-latest
    needs: module-validation
    strategy:
      matrix:
        example: ["1-simple-deployment", "2-complex-deployment"]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init - Example ${{ matrix.example }}
      run: terraform init
      working-directory: examples/${{ matrix.example }}

    - name: Terraform Validate - Example ${{ matrix.example }}
      run: terraform validate
      working-directory: examples/${{ matrix.example }}

    - name: Terraform Plan - Example ${{ matrix.example }}
      run: terraform plan
      working-directory: examples/${{ matrix.example }}
